include:
  - board: nice_nano_v2
    shield: dance_left nice_view_adapter nice_view
  - board: nice_nano_v2
    shield: dance_right nice_view_adapter nice_view
  - board: nice_nano_v2
    shield: settings_reset
  - board: seeeduino_xiao_ble
    shield: dance_dongle prospector_adapter
  - board: seeeduino_xiao_ble
    shield: settings_reset
