include:
  # Split keyboard halves (now peripherals for the dongle)
  - board: nice_nano_v2
    shield: dance_left nice_view_adapter nice_view
    cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
  - board: nice_nano_v2
    shield: dance_right nice_view_adapter nice_view
    cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
  
  # Dongle (central role)
  - board: seeeduino_xiao_ble
    shield: dance_dongle prospector_adapter
  
  # Settings reset for all boards
  - board: nice_nano_v2
    shield: settings_reset
  - board: seeeduino_xiao_ble
    shield: settings_reset
