manifest:
  remotes:
    - name: chase-hunter
      url-base: https://github.com/chase-hunter
    - name: petejohanson
      url-base: https://github.com/petejohanson
    #- name: m165437 #nice-view-gem
    #  url-base: https://github.com/M165437 #nice-view-gem
  projects:
    - name: zmk
      remote: petejohanson
      revision: feat/pointers-with-input-processors
      import: app/west.yml
    - name: nice-view-chase #chase-view
      remote: chase-hunter #chase-view
      revision: main #chase-view
    #- name: nice-shield-p #pig
    # remote: chase-hunter #pig
    # revision: main #pig
    #- name: nice-view-gem #nice-view-gem
    #  remote: m165437 #nice-view-gem
    #  revision: main #nice-view-gem
  self:
    path: config